Repository AHmims/Solder, pull requests merged in 2021-11, with the labels that each got.

#2 Added linter & dedicated build dir, structural changes
  .editorconfig
  .eslintignore
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  queue.json
  solder.config.ts
  src/boot.ts
  src/extensions/manager.ts
  src/extensions/types/extension.type.ts
  src/extensions/types/extensionConfig.type.ts
  src/extensions/types/field.type.ts
  src/extensions/types/item.type.ts
  src/helpers/logger.ts
  src/helpers/text.ts
  src/lib/enums/extension.enum.ts
  src/lib/types/extensions/extension.type.ts
  src/lib/types/extensions/extensionConfig.type.ts
  src/lib/types/extensions/field.type.ts
  src/lib/types/extensions/fieldType.type.ts
  src/lib/types/extensions/fieldValue.type.ts
  src/lib/types/extensions/item.type.ts
  src/lib/types/extensions/scrapMethod.type.ts
  src/lib/types/worker/Queue.type.ts
  src/lib/types/worker/queueFile.type.ts
  src/lib/types/worker/queueJob.type.ts
  src/lib/types/worker/scrapResult.type.ts
  src/modules/electroplanet.json
  src/solder.config.ts
  src/worker/queue.ts
  src/worker/scraper.ts
  src/worker/types/Queue.type.ts
  src/worker/types/queueJob.type.ts
  tsconfig.json
Labels: enhancement, refactor, Reviewed

#5 glow-up-😳 & grow-up-🙈's bastard child
  .env
  .eslintrc.js
  .gitignore
  .prettierrc.js
  modules/electroplanet.json
  package-lock.json
  package.json
  src/boot.ts
  src/extensions/manager.ts
  src/helpers/envy.ts
  src/helpers/logger.ts
  src/helpers/text.ts
  src/lib/enums/extension.enum.ts
  src/lib/types/extension.ts
  src/lib/types/extensions/extension.type.ts
  src/lib/types/extensions/extensionConfig.type.ts
  src/lib/types/extensions/field.type.ts
  src/lib/types/extensions/fieldType.type.ts
  src/lib/types/extensions/fieldValue.type.ts
  src/lib/types/extensions/item.type.ts
  src/lib/types/extensions/scrapMethod.type.ts
  src/lib/types/index.ts
  src/lib/types/indexable.ts
  src/lib/types/worker.ts
  src/lib/types/worker/Queue.type.ts
  src/lib/types/worker/queueFile.type.ts
  src/lib/types/worker/queueJob.type.ts
  src/lib/types/worker/scrapResult.type.ts
  src/solder.config.ts
  src/worker/queue.ts
  src/worker/scraper.ts
  tsconfig.json
Labels: enhancement, refactor, Reviewed

#6 Book of the sun of Docker and the subtelties of elevated things
  .dockerignore
  .editorconfig
  .env
  .eslintrc.js
  .gitignore
  .idea/.gitignore
  .idea/jsLibraryMappings.xml
  .idea/modules.xml
  .idea/solder.iml
  .idea/vcs.xml
  Dockerfile
  Makefile
  docker-compose.prod.yml
  docker-compose.yml
  package-lock.json
  package.json
  redis.conf
  src/config/redis.ts
  src/helpers/envy.ts
  src/helpers/logger.ts
  src/helpers/validator.ts
  src/index.ts
  src/lib/types/index.ts
  src/lib/types/indexable.ts
  src/lib/types/util.ts
  src/lib/types/worker.ts
  src/server/index.ts
  src/server/managers/_blank
  src/server/repositories/_blank
  src/server/routes/index.ts
  src/server/routes/scraper.ts
  src/server/services/_blank
  src/solder.config.ts
  tsconfig.json
Labels: enhancement, Reviewed

#9 Update README.md
  README.md
Labels: Ready for review

#11 Added basic ops to expand upon later
  .github/workflows/docker-build.yml
  .github/workflows/npm-build.yml
Labels: enhancement, Ready for review

#1 Notifications introduction
  .env.dev
  .gitignore
  package.json
  queue.json
  src/helpers/logger.ts
  src/lib/types/request.ts
  src/lib/types/worker.ts
  src/managers/_blank
  src/repositories/_blank
  src/server/index.ts
  src/services/Request/RequestService.ts
  src/services/Webhook/WebhookService.ts
  src/services/_blank
  src/solder.config.ts
  src/worker/queue.ts
  tsconfig.json
Labels: in progress, Ready for review

#12 DARK: Fix queue not working due the latest changes made
  src/lib/types/worker.ts
  src/worker/queue.ts
Labels: bug
